import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app"
import { TRPCReactProvider } from "@/trpc/client";
import { Provider } from "jotai";
import { ThemeProvider } from "next-themes";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <TRPCReactProvider>
          <NuqsAdapter>
          <Provider>
            <ThemeProvider attribute="class" defaultTheme="light">
            {children}
            <Toaster/>
            </ThemeProvider>
          </Provider>
          </NuqsAdapter> 
        </TRPCReactProvider>
      </body>
    </html>
  );
}
